%%{init: {'theme': 'neutral'}}%%
classDiagram
    TechnicalExpertise <|-- SoftwareDev
    TechnicalExpertise <|-- SystemAdmin
    TechnicalExpertise <|-- Cybersecurity
    TechnicalExpertise <|-- CreativeSuite

    class SoftwareDev{
        +Native: [C/C++, Rust, Zig, Go], [Python, Java, Lua]
        +WebStack: [JavaScript, HTML, CSS]
        +WebFrameworks: [Svelte/SvelteKit]
        +Databases: [SQLite, PostgreSQL, MariaDB]
        +Graphics: [OpenGL, SDL3]
        +VersionControl: [Git]
        +Robotics: [ROS]
    }

    class SystemAdmin{
        +LinuxDistributions: [Arch, Debian, RHEL, NixOS]
        +Virtualization: [QEMU/KVM, VMware, Incus]
        +Containerization: [Docker]
        +Orchestration: [K8s]
        +LoadBalancing: [NGINX, Traefik, HAProxy]
        +Automation: [Ansible]
        +Misc: [Bash, PlantUML]
        %% +AndroidTools
    }

    class Cybersecurity{
        +Cryptography: [OpenSSL, GPG]
        +ReverseEngineering: [Assembly, Smali]
        +PenTesting: [nmap, hashcat, Wireshark]
        +Forensics: [photorec]
        +PrivateNetworks: [Tor, I2P]
        +Protocols: [TLS, SSH]
        +Tools: [curl, wget]
    }

    class CreativeSuite{
        +3D: [Blender]
        +2D: [Krita, Inkscape]
        +Video: [OBS, Kdenlive]
        +Audio: [Audacity]
    }
